---
title: "2024 NPORS"
author: "Answers to Questions"
date: "`r Sys.Date()`"
output: 
  pdf_document:
    toc: true
    toc_depth: 2
    keep_tex: true  # Optional, keeps the .tex file for inspection
fontsize: 11pt
geometry: "left=1in,right=1in,top=1in,bottom=1in"
header-includes: 
  - \usepackage{fvextra}
  - \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines, breakanywhere, commandchars=\\\{\}}
---


## Setting Up the Environment

Load the necessary libraries to get started.

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, tidy.opts=list(width.cutoff=60), tidy=TRUE)
library(dyplr)
library(ggplot2)
library(haven) # Load this library to work with .sav files
```

## Setting Up the Directory

Set up the working directory where your data files are stored.

```{r setup-directory}
# Set the working directory to the folder containing your data files
# Replace 'your_directory_path' with the actual path to your directory 
# Set the path to the directory in which the RMD is located
setwd("C:/Users/Ignacio/Dropbox/PhD SBU/06_Teaching/00_POL-501/Problem Sets/PS-2/")

# Confirm the working directory
getwd()
```

## Loading the .sav Dataset

Load the .sav dataset into R.

```{r load-sav-data}
# Replace 'your_dataset.sav' with the path to your actual .sav file
data <- read_sav("NPORS-2024-Data-Release/NPORS_2024_for_public_release.sav")

# View the first few rows of the dataset (glimpse is a function of the dyplr package)
glimpse(data)
```
