---
title: "POL501 - Answers to Problem Set 2"
author: "Student Name (REPLACE)"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: true
    toc_depth: 2
fontsize: 11pt
geometry: "left=1in,right=1in,top=1in,bottom=1in"
---


```{r setup, include=FALSE}
# Load necessary libraries
library(dplyr)
library(ggplot2)
library(haven)
library(tidyverse)
library(formatR)
```

# Question 1

Preliminaries. First, start by declaring the directory (folder) in which you have the data.
```{r, echo=TRUE}
## Setting Up the Directory (REPLACE WITH YOUR FOLDER)
setwd("C:/Users/Ignacio/Dropbox/PhD SBU/06_Teaching/00_POL-501/Problem Sets/PS-2/")

## Confirm the working directory
getwd()
```
Then, load the dataset to memory
```{r, echo=TRUE}
load('/dataframe-ps2.RData')
```

## Answer to (1.a)

## Answer to (1.b)

## Answer to (1.c)

## Answer to (1.d)

## Answer to (1.e)


# Question 2

## Answer to (2.a)

## Answer to (2.b)

## Answer to (2.c)

## Answer to (2.d)

## Answer to (2.e)

## Answer to (2.f)
